--고객 테이블, 실행순서 : 1
CREATE TABLE CUSTOMER (
	`NM` VARCHAR(30) NULL DEFAULT NULL,
	`CONTACT` VARCHAR(15) NULL DEFAULT NULL,
	`ADDR` VARCHAR(50) NULL DEFAULT NULL,
	`SEX` INT(1) NULL DEFAULT NULL,
	`MAIL` VARCHAR(50) NOT NULL,
	`POINT` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`MAIL`)
);
